export const pizza = [
  {
    id: 1,
    name: "پیتزا هالوپینو کلاسیک",
    des: "سس مارینارا, پپرونی, پنیر پیتزا, فلفل هالوپینو",
    price: "445,000",
    price_2: "675,000",
    category: "pizza",
    image: "/1766803006-D3-HV1010www.tiktarh.png",
  },
  {
    id: 1,
    name: "پیتزا چیکن کلاسیک",
    des: "سس مارینارا, فیله مرغ, قارچ, پنیر پیتزا, روچین",
    price: "525,000",
    price_2: "785,000",
    category: "pizza",
    image: "/1766803006-D3-HV1010www.tiktarh.png",
  },
  {
    id: 1,
    name: "پیتزا مخلوط کلاسیک",
    des: "سس مارینارا, ژامبون گوشت و مرغ, قارچ, پنیر پیتزا, روچین",
    price: "475,000",
    price_2: "725,000",
    category: "pizza",
    image: "/1766803006-D3-HV1010www.tiktarh.png",
  },
  {
    id: 1,
    name: "پیتزا تاکو کلاسیک",
    des: "سس مارینارا, گوشت گوساله چرخ شده, قارچ, پنیر پیتزا, روچین",
    price: "595,000",
    price_2: "925,000",
    category: "pizza",
    image: "/rostbif.jpeg",
  },
  {
    id: 1,
    name: "پیتزا چیکن بیف کلاسیک",
    des: "سس مارینارا, فیله مرغ, گوشت گوساله چرخ شده, قارچ, پنیر پیتزا, روچین",
    price: "585,000",
    price_2: "895,000",
    category: "pizza",
    image: "/chbif.jpeg",
  },
  {
    id: 1,
    name: "پیتزا چیکن آلفردو کلاسیک",
    des: "سس آلفردو, فیله مرغ, پنه, قارچ, پنیر پیتزا, روچین",
    price: "-",
    price_2: "895,000",
    category: "pizza",
    image: "/alfredo.jpeg",
  },
  {
    id: 1,
    name: "پیتزا شیگاگو استیک کلاسیک",
    des: "سس مارینارا, استیک گوساله, پنیر پیتزا, روچین",
    price: "585,000",
    price_2: "895,000",
    category: "pizza",
    image: "/1766803006-D3-HV1010www.tiktarh.png",
  },
  {
    id: 1,
    name: "پیتزا رست بیف کلاسیک",
    des: "سس مارینارا, گوشت رست بیف, قارچ, پنیر پیتزا, روچین",
    price: "695,000",
    price_2: "985,000",
    category: "pizza",
    image: "/tako.jpeg",
  },
  {
    id: 1,
    name: "پیتزا گارمون کلاسیک",
    des: "سس آلفردو, فیله مرغ, گوشت رست بیف, ژامبون گوشت و مرغ, قارچ, پنیر پیتزا, روچین",
    price: "-",
    price_2: "985,000",
    category: "pizza",
    image: "/1766803006-D3-HV1010www.tiktarh.png",
  },
];

export const berger = [
  {
    id: 1,
    name: "چیز برگر",
    des: "برگر دست ساز, پنیر ورقه ای",
    price: "465,000",
    price_2: null,
    category: "berger",
    image: "/BG1015286www.tiktarh.com.jpg",
  },
  {
    id: 1,
    name: "برگر فرانسوی",
    des: "برگر دست ساز, قارچ و پنیر",
    price: "525,000",
    price_2: null,
    category: "berger",
    image: "/photo-output.jpeg",
  },
  {
    id: 1,
    name: "برگر مکزیکانو",
    des: "برگر دست ساز, فیله گریل, قارچ و پنیر",
    price: "655,000",
    price_2: null,
    category: "berger",
    image: "/BG1015286www.tiktarh.com.jpg",
  },
  {
    id: 1,
    name: "پولد برگر",
    des: "برگر دست ساز, گوشت رست بیف, قارچ و پنیر",
    price: "695,000",
    price_2: null,
    category: "berger",
    image: "/pold.jpeg",
  },
  {
    id: 1,
    name: " اسلاید برگر",
    des: "برگر دست ساز, 2 ورق ژامبون گوشت, پنیر ورقه ای",
    price: "525,000",
    price_2: null,
    category: "berger",
    image: "/BG1015286www.tiktarh.com.jpg",
  },
  {
    id: 1,
    name: "اسلاید برگر ویژه",
    des: "برگر دست ساز, 2 ورق ژامبون گوشت, بیکن, پنیر ورقه ای",
    price: "595,000",
    price_2: null,
    category: "berger",
    image: "/BG1015286www.tiktarh.com.jpg",
  },
  {
    id: 1,
    name: "سوپر اسلاید برگر",
    des: "2 عدد برگر دست ساز, 2 ورق ژامبون گوشت, بیکن, پنیر ورقه ای",
    price: "895,000",
    price_2: null,
    category: "berger",
    image: "/BG1015286www.tiktarh.com.jpg",
  },
];

export const sib = [
  {
    id: 1,
    name: "سیب زمینی ساده",
    des: "",
    price: "245,000",
    price_2: null,
    category: "sib",
    image: "/Cart1026666www.png",
  },
  {
    id: 1,
    name: "سیب زمینی با قارچ و پنیر",
    des: "",
    price: "415,000",
    price_2: null,
    category: "sib",
    image: "/Cart1026666www.png",
  },
  {
    id: 1,
    name: "سیب زمینی با سس قارچ",
    des: "",
    price: "465,000",
    price_2: null,
    category: "sib",
    image: "/Cart1026666www.png",
  },
  {
    id: 1,
    name: "سیب زمینی ویژه",
    des: "سیب زمینی, قارچ و پنیر, ژامبون گوشت",
    price: "455,000",
    price_2: null,
    category: "sib",
    image: "/photo-output (2).jpeg",
  },
  {
    id: 1,
    name: "سیب زمینی سوپرمکزیکی",
    des: "سیب زمینی, قارچ و پنیر, ذرت, فیله گریل",
    price: "(دونفره) 685,000",
    price_2: null,
    category: "sib",
    image: "/Cart1026666www.png",
  },
  {
    id: 1,
    name: "سیب زمینی ساوالان",
   des: "سیب زمینی, قارچ و پنیر, ژامبون گوشت, هات داگ پنیری",
    price: "(دونفره) 685,000",
    price_2: null,
    category: "sib",
    image: "/photo-output (1).jpeg",
  },
  {
    id: 1,
    name: "سیب زمینی فرنگی",
   des: "سیب زمینی, قارچ و پنیر, ژامبون گوشت, برگر دست ساز",
    price: "(دونفره) 835,000",
    price_2: null,
    category: "sib",
    image: "/Cart1026666www.png",
  },
  {
    id: 1,
    name: "سیب زمینی گارمون",
    des: "سیب زمینی, قارچ و پنیر, ژامبون گوشت, فیله گریل, هات داگ پنیری, برگر دست ساز",
    price: "(سه نفره) 985,000",
    price_2: null,
    category: "sib",
    image: "/sibG.jpeg",
  },
];

export const sandvich = [
  {
    id: 1,
    name: "ساندویچ سرد",
    des: "ژامبون گوشت یا ژامبون مرغ یا ژامبون میکس",
    price: "425,000",
    price_2: null,
    category: "sandvich",
    image: "/Cart1027416www.png",
  },
  {
    id: 1,
    name: "ژامبون تنوری",
    des: "ژامبون گوشت, ژامبون مرغ, قارچ, پنیر",
    price: "465,000",
    price_2: null,
    category: "sandvich",
    image: "/zambon.jpeg",
  },
  {
    id: 1,
    name: "آفریکانو",
    des: "هات داگ پنیری, ژامبون گوشت, قارچ و پنیر, فیله گریل",
    price: "585,000",
    price_2: null,
    category: "sandvich",
    image: "/Cart1027416www.png",
  },
  {
    id: 1,
    name: "فیله پالرمو",
     des: "ژامبون گوشت, قارچ و پنیر, فیله گریل",
    price: "475,000",
    price_2: null,
    category: "sandvich",
    image: "/Cart1027416www.png",
  },
  {
    id: 1,
    name: "هات داگ رویال",
    des: "هات داگ پنیری, ژامبون گوشت, قارچ و پنیر",
    price: "435,000",
    price_2: null,
    category: "sandvich",
    image: "/Cart1027416www.png",
  },
  {
    id: 1,
    name: "رست بیف",
    des: "گوشت رست بیف, سس قارچ, پنیر پیتزا",
    price: "725,000",
    price_2: null,
    category: "sandvich",
    image: "/Cart1027416www.png",
  },
  {
    id: 1,
    name: "ساندویچ گارمون",
    des: "برگر دست ساز, فیله گریل, ژامبون گوشت, قارچ و پنیر, 2 عدد هات داگ پنیری",
    price: "(دونفره) 965,000",
    price_2: null,
    category: "sandvich",
    image: "/Cart1027416www.png",
  },
];

export const pasta = [
  {
    id: 1,
    name: "پاستا چیکن آلفردو",
    des: "فیله مرغ, پنه, سس آلفردو, قارچ, پنیر پارمسان",
    price: "595,000",
    price_2: null,
    category: "pasta",
    image: "/pasta.jpeg",
  },
  {
    id: 1,
    name: "پاستا بیف آلفردو",
    des: "گوشت گوساله, پنه, سس آلفردو, قارچ, پنیر پارمسان",
    price: "725,000",
    price_2: null,
    category: "pasta",
    image: "/1774946727-Cart1043015www.png",
  },
  {
    id: 1,
    name: "نان سیر",
    des: "حریره سیر, پنیر پیتزا",
    price: "285,000",
    price_2: null,
    category: "pasta",
    image: "/sir.jpeg",
  },
  {
    id: 1,
    name: "سالاد سزار",
    des: "کاهو, سس سزار, فیله, نان سیر, پنیر پارمسان",
    price: "525,000",
    price_2: null,
    category: "pasta",
    image: "/szar1.jpeg",
  },
];
